bracesdev/errtrace

.github/workflows/ci.yml
.gitignore
Makefile
codecov.yml

Tracks coverage from all three test runs,
and merges them using the Go coverage redesign.
The reports are uplodaed to codecov,
which will further merge all per-system/per-job coverage reports.

ci: Track coverage with codecov.io

---

CHANGELOG.md
Makefile
README.md

Unfortunately, pkg.go.dev renders README.adoc
as a plain text with .adoc syntax showing.
Used [docdown](https://github.com/opendevise/downdoc)
to conver the adoc back to Markdown and tweaked the result manually.

README: Back to Markdown

---

CHANGELOG.md
cmd/errtrace/main.go
cmd/errtrace/main_test.go
cmd/errtrace/testdata/golden/noop.go
cmd/errtrace/testdata/golden/noop.go.golden

Adds an -l flag to the errtrace command
that lists files that would be changed by the command
without actually changing them.
This will make it easier for projects to add a lint check
which verifies that the files are up-to-date.

cmd/errtrace: Add -l flag

---

README.md

Correct the typographical atrocities perpetrated in this README by
replacing `--` with proper em-dashes. Hyperbole aside, this ends up
looking better and reading more easily.
I chose to use `&mdash;` instead of `—` because IMO it's a little easier
to work with in text editors. Happy to switch if you'd prefer.

Replace double hyphens with em-dashes

---

CHANGELOG.md
README.md
cmd/errtrace/main.go
cmd/errtrace/main_test.go
cmd/errtrace/testdata/golden/noop.go
cmd/errtrace/testdata/golden/noop.go.golden
cmd/errtrace/testdata/golden/optout.go
cmd/errtrace/testdata/golden/optout.go.golden

Affected lines may add `//errtrace:skip`
to opt-out of being instrumented.
This is necessary for types implementing `io.Reader`;
they must return `io.EOF`, not `fmt.Errorf("%w", io.EOF)`,
or functions like `io.ReadAll` will misbehave[^1].
[^1]: https://cs.opensource.google/go/go/+/refs/tags/go1.21.4:src/io/io.go;l=707
---
`//errtrace:skip` makes sense as the opt-out to me,
but I'm open to other suggestions.

cmd/errtrace: Support opt-out with //errtrace:skip

---

cmd/errtrace/main.go
cmd/errtrace/main_test.go
cmd/errtrace/testdata/golden/noop.go
cmd/errtrace/testdata/golden/noop.go.golden
cmd/errtrace/testdata/golden/optout.go
cmd/errtrace/testdata/golden/optout.go.golden

If we find `//errtrace:skip` comments on lines
that wouldn't be instrumented, print warnings about them.
Resolves #61

cmd: Warn on unused //errtrace:skip

---

README.md

A common question is how error traces differ from
stack traces, so add an explicit section that
covers this aspect, and move the HTTP example
into this section, as it highlights the difference.

Add section comparing errtrace to stack traces

---

README.md
cmd/errtrace/main.go
cmd/errtrace/testdata/golden/optout.go
cmd/errtrace/testdata/golden/optout.go.golden

strings.Contains is too wide for this purpose.
It trips up even if a doc comment mentions '//errtrace:skip'.
Narrow it down to a much more selective criteria:
- must be a single line comment
- must be at start of the comment (`foo() //errtrace:skip`)
or have a space immediately before it (`foo() //nolint:bar //errtrace:skip`)
- must reach end of the comment (`foo() //errtrace:skip`)
or have a space (`foo() //errtrace:skip //nolint:bar`)
or an opening parenthesis (`foo() //errtrace:skip(reason)`)
immediately after it.

cmd/errtrace: Tighten up opt-out matching

---

internal/pc/pc_safe.go

The const was declared
but not used.
Resolves #68

pc_safe: use skip const

---

wrap.go

The signature of these functions is a little strange, so let's add some context for how they're used, especially the CLI usage to avoid file:line changes.

Add more context to WrapN docs

---

CHANGELOG.md
cmd/errtrace/main.go
cmd/errtrace/main_test.go

One thing that can be confusing about the UX of the CLI is that
when you call it without any arguments,
it's reading from stdin but you may not know that.
You may assume it's just taking forever to start up.
This changes it to print a message to stderr
if it's reading from stdin because no arguments were given.

cmd: Print a message when reading from stdin implicitly

---

CHANGELOG.md
README.md
cmd/errtrace/main.go
cmd/errtrace/main_test.go

Adds support to the errtrace command
for recognizing import path patterns.
This makes the common case for command usage:
errtrace -w ./...
This is an optional addition to the existing file-based behavior.
If the provided argument is an existing file, it will be used as-is.
Otherwise, the pattern will be expanded with`go list`.
If a pattern is provided, all matching Go files are in-scope:
source, test, and external tests and build-tagged files.
Resolves #73

cmd: Support package patterns

---

cmd/errtrace/main.go
cmd/errtrace/main_test.go

Follow-up to #78 and #82.
When stdin is implicitly used, we wait for 200ms for input before printing a message to stderr to notify the user that we're reading from stdin to avoid confusion. This added some complexity in the read path, as well as the testing because of the background goroutine that waits for a timeout before printing to stderr.
This is an alternative approach that does a best-effort detection of a TTY by checking if stdin is a character device.

cmd/errtrace: Best-effort detection of tty stdin using char device

---

.github/workflows/ci.yml

Add Go 1.22 to the matrix, leave 1.20 in for now.
When we delete 1.20, we should bump the go.mod to 1.21.

ci: Test with Go 1.22

---

CHANGELOG.md
cmd/errtrace/main.go
cmd/errtrace/main_test.go

This is a pretty standard CLI behavior:
`cmd -h` should print the help message and exit with status 0.
This is the default behavior in the flag package under ExitOnError mode.
We neglected to replicate that in ContinueOnError mode.

cmd: Exit with status 0 when `-h` is used

---

cmd/errtrace/main.go
cmd/errtrace/testdata/main/foo/foo.go
cmd/errtrace/testdata/main/go.mod
cmd/errtrace/testdata/main/go.sum
cmd/errtrace/testdata/main/main.go
cmd/errtrace/testdata/toolexec-test/errtrace.go
cmd/errtrace/testdata/toolexec-test/main.go
cmd/errtrace/testdata/toolexec-test/p1/p1.go
cmd/errtrace/testdata/toolexec-test/p2/errtrace.go
cmd/errtrace/testdata/toolexec-test/p2/p2.go
cmd/errtrace/testdata/toolexec-test/p3/errtrace.go
cmd/errtrace/testdata/toolexec-test/p3/p3.go
cmd/errtrace/toolexec.go
cmd/errtrace/toolexec_test.go

Fixes #17
The go command supports `-toolexec` to intercept calls to the underlying compile/link tools.
By intercepting compile commands, we can modify the .go files passed to it to rewrite as
part of the build process.
There are some limitations: we can't add new dependencies to a package, so this initial version
only rewrites packages that already import errtrace, acting as an opt-in to rewriting.
We automatically determine if we're in toolexec mode based on the arguments/environment.
This simplifies usage,
```
$ go build -toolexec=errtrace pkg/to/build
$ go run -toolexec=errtrace pkg/to/run
```

cmd/errtrace: Add toolexec mode for automatic rewriting

---

cmd/errtrace/main.go
cmd/errtrace/testdata/golden/imported_blank.go
cmd/errtrace/testdata/golden/imported_blank.go.golden
cmd/errtrace/testdata/toolexec-test/errtrace.go
cmd/errtrace/testdata/toolexec-test/main.go
cmd/errtrace/toolexec.go

With toolexec mode, a blank import of errtrace is more likely to opt-in to rewriting. However, this blank import can't be used to call errtrace functions, so we need to track both:
* Whether errtrace is imported (used to opt-in toolexec rewriting)
* Whether errtrace needs to be imported for any Wrap calls.
Since this change modifies the rewriting logic, we bump the errtrace toolexec version manually.

cmd/errtrace: Fix blank import handling

---

cmd/errtrace/toolexec.go

The toolexec version should be bumped on any change to the code rewriting. Doing this manually is error-prone, so instead, use a string that uniquely identifies the errtrace binary. Note that every time this version changes, it means the build cache can't be used so it's important to use a stable value.
We default to the git SHA in the debug build info (vcs.revision) if the binary is build from a clean state (vcs.modified=false).
Otherwise, we use the MD5 of the binary being executed. This is more expensive than the SHA to compute, so we prefer the SHA.

cmd/errtrace: Uniquely identify the binary for toolexec version

---

cmd/errtrace/slices_contains_go121.go
cmd/errtrace/slices_contains_pre_go121.go
cmd/errtrace/testdata/toolexec-test/main_test.go
cmd/errtrace/toolexec.go
cmd/errtrace/toolexec_test.go

When compiling files passed as command line arguments, go uses a special
package name, "command-line-arguments". Similarly for tests, it uses
"command-line-arguments.test".
Rather than hardcoding these special package names, let's update the
stdlib detection to:
* Rule out any package with "." (as no stdlib packages contain periods)
* Look for "-std" in the arguments passed to compile
Update the toolexec tests to compile with files passed directly on the
command line, and verify both "go run" and "go build".

cmd/errtrace: Fix toolexec with `go run main.go`

---

cmd/errtrace/main.go
cmd/errtrace/main_test.go
cmd/errtrace/testdata/golden/no-wrapn.go
cmd/errtrace/testdata/golden/no-wrapn.go.golden
cmd/errtrace/testdata/golden/simple.go
cmd/errtrace/testdata/golden/simple.go.golden
cmd/errtrace/testdata/golden/wrapn.go.golden
cmd/errtrace/toolexec.go

This unblocks #91, as `go:linkname` can't be used to link to generic functions, which `WrapN` functions rely on.
Rewrites use temporary variables to hold the returns from a function call before returning, wrapping the error with `Wrap`:
```
return SomeFuncCall()
{ r1, ..., rN := SomeFuncCall(); return r1, ..., errtrace.Wrap(rN) }
```
A new scope is used to ensure variables don't clash, avoiding the need to track what variables are in scope.
Most of our golden files aren't impacted by this change, so we run tests with no options, and with no-wrapn. For tests that are impacted, they specify which options are required to run the test.

cmd/errtrace: Add no-wrapn option to avoid WrapN usage

---

.github/workflows/ci.yml
cmd/errtrace/main.go

In #95, we added an nVars function to generate a list of variable
names with a common prefix.
The function didn't actually use the prefix.
This commit fixes that.

cmd: fix(nVars): Actually use prefix

---

.github/workflows/ci.yml

Adds a dummy ci-ok job that depends on the lint and test job matrix.
This will allow us to add a single Required Status Check to the
protected branch instead of trying to add every variation of the test
job matrix to it.

ci: Add "ci-ok" job

---

cmd/errtrace/testdata/golden/named_returns.go
cmd/errtrace/testdata/golden/named_returns.go.golden

We go to some lengths to make sure that
we're tracking the correct named return value in assignments,
but we don't have a test for it.
This adds a test that verifies that if a named return value is shadowed,
the shadowed value is not wrapped if it's not otherwise in scope for
wrapping.

Add test for shadowing named return value

---

CHANGELOG.md
cmd/errtrace/main.go
cmd/errtrace/testdata/golden/tuple_rhs.go
cmd/errtrace/testdata/golden/tuple_rhs.go.golden

In #96, @DavidArchibald reported (and provided a fix for)
a bug where the following would cause a panic:
```go
func f() (err error) {
defer func() {
_, err = fmt.Println("Hello, World!")
}()
return nil
}
```
The panic was:
```
panic: runtime error: index out of range [1] with length 1 [recovered]
panic: runtime error: index out of range [1] with length 1
goroutine 180 [running]:
testing.tRunner.func1.2({0x1002cc500, 0x14000014a08})
[..]/go/1.22.2/libexec/src/testing/testing.go:1631 +0x1c4
testing.tRunner.func1()
[..]/go/1.22.2/libexec/src/testing/testing.go:1634 +0x33c
panic({0x1002cc500?, 0x14000014a08?})
[..]/go/1.22.2/libexec/src/runtime/panic.go:770 +0x124
braces.dev/errtrace/cmd/errtrace.(*walker).deferStmt.func1({0x1002df7a0?, 0x1400028e080}) …
```

fix(cmd): Handle imbalanced LHS and RHS in defer assignment

---

CHANGELOG.md

Adds entries to the changelog for the new toolexec mode
and the -no-wrapn flag.
toolexec mode is advertised as experimental for now.

CHANGELOG: Add entries for toolexec and -no-wrapn

---

.golangci.yml
cmd/errtrace/main.go
cmd/errtrace/toolexec.go

errtrace is flagging a few fmt.Fprint{f,ln} calls. Fix them by:
* Adding error checks to writes that are required for functionality
* Use separate `log{f,ln}` functions for non-required writes intended
for logging, and ignore errors in the log functions.
* Ignore write errors to `fmt.State`

Fix lint errors

---

example_errhelper_test.go
internal/pc/pc_amd64.s
internal/pc/pc_arm64.s
internal/pc/pc_asm.go
internal/pc/pc_safe.go
wrap_caller.go
wrap_caller_safe_test.go
wrap_caller_test.go

Fixes #70
`errtrace.Wrap` captures the immediate caller, which doesn't compose
with existing error-wrapping helpers. To support this use-case, add
`errtrace.GetCaller()` that helpers can use to capture their caller
and add that to the error trace.
This approach was chosen over the typical `skip` callers as:
* Skip requires a more complex assembly implementation to skip an
arbitrary number of frames, which is more error-prone, e.g.,
handling the skip argument being too large.
* Faster as each call only skips a fixed (and predictable) number of
frames. This is especially important since it's expected that
`errtrace` is used to annotate all frames in the return path.
* Avoids skip calculations, and generally more flexible to pass around
compared to skipping frames, which is tied to the …

Add GetCaller for use in error helpers

---

CHANGELOG.md
assets/go.mod
benchext/go.mod
cmd/errtrace/main_test.go
cmd/errtrace/toolexec_test.go
go.mod

Follow-up to #110, we no longer test 1.20 so go.mod should be updated
and we can drop TODOs related to supporting 1.20.

Drop go 1.20 support, update go.mod to 1.21

---

.github/workflows/ci.yml

I missed CHANGELOG updates in a couple of recent PRs, so figured a CI
check may be a helpful reminder.
Not every PR needs a CHANGELOG, so skips are supported via a
customizable label, which I've set to `skip-changelog`.

ci: Add check to ensure CHANGELOG is updated

---

.github/workflows/ci.yml

`*` doesn't match `/`:
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
With stacked PRs, the base branch could be `prashant/base`, which
doesn't currently match, and hence wasn't running CI.

ci: Run on PRs against all base branches

---

internal/diff/diff.go

Go 1.21 added built-ins for `min` and `max`.

Fix lint: redefines-builtin-id for max

---

CHANGELOG.md
cmd/errtrace/toolexec.go
cmd/errtrace/toolexec_test.go

toolexec mode only rewrites packages that have import the errtrace
package, and others are silently ignored which can lead to unintended
missed rewrites.
Accept package selectors of packages that must import errtrace if a
rewrite is required.
Most of this change is setting up the machinery for toolexec flags:
- Set up a new flagset for toolexec flags, which are only parsed once
we know we're in toolexec mode.
- Include a hash of the flag values in the version key as a previously
cached output may not be valid when flags change. E.g., a previous
package success should fail if the required-packages flag changes and
it contains a package that needs a rewrite but is missing the import.

toolexec: Add required-packages flag

---

.github/workflows/ci.yml
.golangci.yml

Change CI to test with Go 1.24 and drop 1.21.
Migrate the golangci-lint config to v2 format
as that's the default for the golangci-lint GitHub Action now.

Update to golangci-lint v2, Go 1.24

---

CHANGELOG.md
errtrace.go
example_trace_test.go

Go 1.21 adds the `log/slog` package and this PR adds convenience and compatibility with that package. Merging this PR would require dropping Go 1.20 support, which may not (yet!) be desired. If so, this PR can wait until that is desired.
Each major Go release is supported until there are two newer major releases. Go 1.22 was released on February 6, 2024
so Go 1.20 is no longer supported.

Add slog compatibility
